# Generated by Django 5.2.5 on 2025-10-01 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Invalid Username', message='Username can only contain letters, numbers, and underscores \nHint: @/[1-10][a-z][A-Z]', regex='^[a-zA-Z0-9_]*$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='Invalid Password', message='Password can only contain letters, numbers, and underscores.\nHint: @/[1-10][a-z][A-Z]', regex='^[a-zA-Z0-9_]*$')])),
            ],
        ),
    ]
