# Generated by Django 5.2.5 on 2025-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='APP/static/actors'),
        ),
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='APP/static/directors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='APP/static/movies'),
        ),
        migrations.AddField(
            model_name='movieactor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='APP/static/movie-actor'),
        ),
    ]
