# Generated by Django 5.2.5 on 2025-10-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profile_Picture',
            field=models.ImageField(default='', upload_to='APP/static/users'),
        ),
    ]
